### ISSUE TITLE
Maybe hack nitro accounts like that?

### ISSUE THREAD

**Issue by JokersCat** [xtekky/Discord-Token-Gen#1]
So you can read out the timestamp when a account was created I think and the user id is also public so when you would own a botnet or something it would go relatively fast to bruteforce a 27 letter string of course you would need a huge botnet

**Comment by ghost** [comment]
lmfao gl with that

**Comment by JokersCat** [comment]
idk I dont own a botnet so yeah idk xD

**Comment by xtekky** [comment]
yes you can do it an more power u have, more it will be faster

**Comment by pyrgasm** [comment]
Lmao my guy, no botnet will help you with that lol good luck "bruteforcing" 21482769967099999998512245106093322829427638272 possibilities its 52 chars ^ 27 length

**Comment by JokersCat** [comment]
I mean just make a list with all that positivities split that list over all pcs and yeah that’s it
